version: "3.3"
services:
  postgres:
    image: postgres
    container_name: trajectory_postgres
    environment:
      POSTGRES_DB: cooking
      POSTGRES_USER: trajectory_user
      POSTGRES_PASSWORD: trajectory_password
      referenceUrl: 'hibernate:spring:entity?dialect=org.hibernate.dialect.PostgreSQL10Dialect&hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
    ports:
      - "5433:5432"
  trajectory-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/cooking
      - SPRING_DATASOURCE_USERNAME=trajectory_user
      - SPRING_DATASOURCE_PASSWORD=trajectory_password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver